server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: ${APPLICATION_NAME:userservice}
  config:
    import: optional:file:.env[.properties]
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/platform?currentSchema=${spring.application.name}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: ${spring.application.name}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: trace

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
    prefer-ip-address: true



