server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: ${APPLICATION_NAME:user-service}
#  datasource:
#    url: j${DB_URL:jdbc:postgresql://localhost:5432/platform?currentSchema=${spring.application.name}}
#    username: user
#    password: pass
#    driverClassName: org.postgresql.Driver
#  jpa:
#    hibenate:
#      ddl-auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

  profiles:
    active: prod


