server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: ${APPLICATION_NAME:userservice}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/platform?currentSchema=${spring.application.name}}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: ${spring.application.name}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: trace

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

#  profiles:
#    active: prod


